[package]
name = "kolloquy"
version = "0.1.0"
edition = "2021"
authors = ["ljpprojects <owner@ljpprojects.org>"]

[lib]
crate-type = ["cdylib"]

# No but really Kolloquy is heading the same way
# Even when they were available to use
# They went nowhere
# And its the same with lmnopGAME
# It might even be an actively harmful
#
# Hell
# Why even renew my domains next year
# Its not like anyone visits them
# Its a waste of $30 a year
# I will start a challenge
# Take down my whole website fully
# Until either the domain registration expires
# Or someone notices
# And the same with Kolloquy, Mosaic, and lmnopGAME
# Full cessation of development until someone notices (they literally cant because I have been pouring years of efforts into a void)
# Okay maybe not lmnopGAME
# I am dependent on that
# The things I'd do without it...
# The things I'd have done without it...
# But everything else dies

[profile.release]
lto = "fat"
codegen-units = 1
opt-level = 3
panic = "abort"
debug = "none"
strip = true

[workspace]
resolver = "3"
members = ["kolloquy-consts", "kolloquy-crypto", "kolloquy-state", "kolloquy-phash"]

[dependencies.worker]
version = "0.7"
features = ["http", "d1", "axum"]

[dependencies.axum]
version = "0.8"
default-features = false
features = ["json", "macros"]

[dependencies.serde_json]
version = "1.0"
default-features = false

[dependencies.serde]
version = "1.0"
default-features = false
features = ["serde_derive"]

[dependencies.url]
version = "2.5"
default-features = false

[dependencies.base64]
version = "0.22"
default-features = false

[dependencies.web-sys]
version = "0.3"
default-features = false
features = ["Crypto", "Window", "SubtleCrypto", "CryptoKey"]

[dependencies.handlebars]
version = "6.4"
default-features = false
features = ["no_logging"]

[dependencies.chrono]
version = "0.4"
default-features = false

[dependencies.hex]
version = "0.4"
default-features = false

[dependencies]
http = "1.4"
tower-service = "0.3"
tower-http = { version = "0.6", features = ["cors"] }
wasm-bindgen-futures = "0.4"
wasm-bindgen = "0.2"
axum-cookie = "0.2"
const_format = "0.2"
stackvec = "0.2"
stack-string = "1.1.5"
password-hash = { version = "0.6.0-rc.12", features = ["phc"] }
rlsf = "0.2.2"
arrayvec = { version = "0.7.6", features = ["serde"] }
webauthn-rs-proto = "0.5"
base64urlsafedata = "0.5"
