http {
    server_tokens off;

    # Cache hits are exempt from the global rate limit (as they don't reach the backend)
    map $upstream_cache_status $limit_key_g {
        default "g";
        HIT     "";
    }

    # Global rate limiting based on total request volume across all clients
    limit_req_zone $limit_key_g zone=phash_req_g:5m rate=10r/s;
    limit_conn_zone "g" zone=phash_conn_g:10m; # Global max connections limit remains even for cache hits

    # Level 1 applies to everything but cache hits (as those never reach the backend)
    map $upstream_cache_status $limit_key_l1 {
        default $binary_remote_addr;
        HIT     "";
    }

    # Rate limit of 1req/s per client, for cache misses
    limit_req_zone $limit_key_l1 zone=phash_req_l1:5m rate=1r/s;

    # Level 2 to applies to cache hits only.
     map $upstream_cache_status $limit_key_l2 {
        default "";
        HIT     $binary_remote_addr;
    }

    # Rate limit of 8req/s per client, for cache hits
    limit_req_zone $limit_key_l2 zone=phash_req_l2:1m rate=8r/s;

    proxy_cache_path
        /home/klqy/cache
        levels=1:2
        keys_zone=hash_cache:25m
        max_size=4g
        inactive=60d # If a hash hasnt been needed for 2 months we can afford to recompute it when it is needed
        use_temp_path=off;

    server {
        listen 443 ssl;
        listen [::]:443 ssl;
        server_name phash.kolloquy.com;

        ssl_certificate /home/klqy/phash/mtls.crt;
        ssl_certificate_key /home/klqy/phash/mtls.key;

        ssl_client_certificate /home/klqy/phash/mtls-ca.crt;
        ssl_verify_client on;
        ssl_verify_depth 1;

        ssl_protocols TLSv1.2 TLSv1.3;

        error_log /home/klqy/phash/log/errors.log warn;

        # Requests go to /{digest}, so we can just redirect from kolloquy.phash.com/* (or wherever you host the server) to 127.173.197.139:7399/*
        location / {
            proxy_cache hash_cache;
            proxy_cache_methods GET HEAD POST;
            proxy_request_buffering on;
            client_body_buffer_size 16k;
            client_max_body_size 16k;

            # Level 0 (global)

            limit_req zone=phash_req_g burst=100;
            limit_req_status 429;

            limit_conn phash_conn_g 8;
            limit_conn_status 503;

            # Level 1 (per-client, cache misses)
            limit_req zone=phash_req_l1 burst=4;

            # Level 2 (per-client, cache hits)
            limit_req zone=phash_req_l2 burst=8;

            # Ignore 127 (required for loopback) and 1s (they are required for
            # digits 2-9)
            proxy_pass http://127.173.197.139:7399/;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_cache_use_stale error timeout updating;
            proxy_cache_background_update on;
            proxy_cache_key $request_body;

            # Last time I checked hashes don't change if the data is the same...
            # If it does a full cache purge is needed anyway
            proxy_cache_valid 200 69y;

            # We won't cache errors

            add_header X-Cache-Status $upstream_cache_status;
            add_header Cache-Control "public, max-age=31536000, immutable";
        }
    }
}